In [1]:
import numpy as np

In [2]:
# Creating a numpy array from a single list to get a 1-D array
my_list=[3,4,5,8,4]
create_1d_arr = np.array(my_list)

#casting a list of list to get a 2-D array
list_2 = [[4,5,6],[1,4,5],[9,0,1],[5,2,9]]
create_2d_arr = np.array(list_2)

In [3]:
# Creating Numpy array using arange() built in function
list_3 = np.arange(20)

# generating a 1-D  array of zeros and ones
my_zeros = np.zeros(5)
my_ones = np.ones(5)

# creating a 2-D array of zeros
two_d = np.zeros((4,3))

In [4]:
# Creating Numpy array using linspace()
lin_arr = np.linspace(1,10,14)

# Creating an identity matrix using eye() function
identity_mat = np.eye(5) # takes a single arg which means the tot num of rows and col


# Generaing arrays of random numbers

# rand() function generates random numbers btw 0-1 based on the specified shape
my_rand1 = np.random.rand(4)

# 2-D array using rand()
my_rand2 = np.random.rand(3,5)

# working with randn function
my_rand3 = np.random.randn(5)

# Working with randint() fucntion
my_rand4 = np.random.randint(10)

In [5]:
# Converting 1-D array to 2-D array using reshape
convert = np.random.randn(25)
convert.reshape(5,5)

# Locating the maximum and minimum value in an array using max() and min()
arr_1 = np.random.randint(0,20,15)
arr_1.max() # this gives the largest value in the array
arr_1.min() # this gives the lowest value in the array


# using argmax() and argmin() to locate the index of the largest and lowest value
arr_1.argmax() # index of highest value
arr_1.argmin() # index of lowest value 


# check if an array is 1-D or 2-D,we use the shape function
my_rand2.shape
my_rand3.shape

(5,)

In [6]:
# Indexing or seleceting elements from a numpy array
my_array = np.arange(0,20)
my_array[4] # element at index 4

# we use slice ':' notattion to get range of values in an array
my_array[2:4] # elements btwn index 2 and 4-1

my_array[:5] # elements between the start of the array and index 5-1

my_array[5:] # range of elemets starting from index 5 till the end of the array


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
# Selecting elements from a 2-D array using double [][] or [,] notation
two_d_arr = np.array([[40,1,33,5],[90,2,15,6],[23,12,5,76]])

two_d_arr[1,2] # getting the element 15 using double bracket notation

two_d_arr[2,2] #getting the element 5 using the single bracket notation

5

In [18]:
# Creating rsndon integers in a specific range

np.random.randint(9, size=7) # 1-Dimensional

np.random.randint(9, size=(3,3)) # 2- Dimensional

# Creating random float between 0 and 1

np.random.random(9)

# Creating sample from a standard normal distribution

np.random.randn(100)

# Creating a matrix with a single element

np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# Manipulating array-- using ravel function to flatten a 2-D array
two_d_array = np.random.randint(7, size=(4,4))

# flattening the array above with ravel function
two_d_array.ravel()

# reshaping an array by specifying dimension
two_d_array.reshape((2,8))

# allowing numpy to reshape itself by using -1

two_d_array.reshape(-1,4)

# Transposing a matrix

two_d_array.transpose()

array([[0, 6, 6, 6],
       [1, 2, 2, 3],
       [1, 4, 4, 1],
       [5, 0, 3, 2]])